float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: ZillizCloud
      disabled: false
      docker_tag: ann-benchmarks-zilliz_cloud
      module: ann_benchmarks.algorithms.zilliz_cloud
      name: zilliz_cloud
      run_groups:
        AUTOINDEX:
          args:
            user: ""
            password: ""
            uri: ""
