float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: ZillizCloud
      disabled: false
      docker_tag: ann-benchmarks-zilliz_cloud
      module: ann_benchmarks.algorithms.zilliz_cloud
      name: zilliz_cloud
      run_groups:
        AUTOINDEX:
          args: ["test-args-1", "test-args-2"]
          query_args: ["test-query_args-1", "test-query_args-2"]
