float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: ZillizCloud
      disabled: false
      docker_tag: ann-benchmarks-zilliz_cloud
      module: ann_benchmarks.algorithms.zilliz_cloud
      name: zilliz_cloud
      run_groups:
        AUTOINDEX:
          args:
            uri: ""
            user: ""
            password: ""
            skip_insert: false # skip creating collection, inserting data and building indexes
          query_args: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30]] # concurrencies for batch mode; nothing would happen in single-query mode;
